// <auto-generated />
using System;
using MathApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathApi.Migrations
{
    [DbContext(typeof(MathDbContext))]
    [Migration("20230804092824_FixRelations2")]
    partial class FixRelations2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MathApi.Models.Axiom", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Axioms");
                });

            modelBuilder.Entity("MathApi.Models.AxiomProposition", b =>
                {
                    b.Property<long>("AxiomId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.HasKey("AxiomId", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.ToTable("AxiomPropositions");
                });

            modelBuilder.Entity("MathApi.Models.Formula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Meaning")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("MathApi.Models.FormulaChain", b =>
                {
                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FromFormulaStringSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("ToFormulaStringSerialNo")
                        .HasColumnType("bigint");

                    b.HasKey("FormulaId", "SerialNo");

                    b.HasIndex("FormulaId", "FromFormulaStringSerialNo")
                        .IsUnique();

                    b.HasIndex("FormulaId", "ToFormulaStringSerialNo")
                        .IsUnique();

                    b.ToTable("FormulaChains");
                });

            modelBuilder.Entity("MathApi.Models.FormulaString", b =>
                {
                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("SymbolId")
                        .HasColumnType("bigint");

                    b.HasKey("FormulaId", "SerialNo");

                    b.HasIndex("SymbolId");

                    b.ToTable("FormulaStrings");
                });

            modelBuilder.Entity("MathApi.Models.FormulaType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormulaTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Term"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Proposition"
                        });
                });

            modelBuilder.Entity("MathApi.Models.Inference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAssumptionAdd")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBasic")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TheoremId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TheoremId")
                        .IsUnique();

                    b.ToTable("Inferences");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgument", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int>("InferenceArgumentTypeId")
                        .HasColumnType("int");

                    b.Property<long?>("VariableSymbolId")
                        .HasColumnType("bigint");

                    b.HasKey("InferenceId", "SerialNo");

                    b.HasIndex("InferenceArgumentTypeId");

                    b.HasIndex("VariableSymbolId");

                    b.ToTable("InferenceArguments");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgumentConstraint", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("InferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int>("ConstraintDestinationInferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<bool>("IsConstraintPredissolvedAssumption")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("InferenceId", "InferenceArgumentSerialNo", "SerialNo");

                    b.HasIndex("InferenceId", "ConstraintDestinationInferenceArgumentSerialNo");

                    b.ToTable("InferenceArgumentConstraints");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InferenceArgumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "term"
                        },
                        new
                        {
                            Id = 2,
                            Name = "proposition"
                        },
                        new
                        {
                            Id = 3,
                            Name = "free variable"
                        });
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumption", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int>("InferenceAssumptionDissolutionTypeId")
                        .HasColumnType("int");

                    b.HasKey("InferenceId", "SerialNo");

                    b.HasIndex("InferenceAssumptionDissolutionTypeId");

                    b.ToTable("InferenceAssumptions");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionDissolutableAssumptionFormula", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("InferenceAssumptionSerialNo")
                        .HasColumnType("int");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("BoundInferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("InferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentFromSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentToSerialNo")
                        .HasColumnType("int");

                    b.Property<long?>("SymbolId")
                        .HasColumnType("bigint");

                    b.HasKey("InferenceId", "InferenceAssumptionSerialNo", "SerialNo");

                    b.HasIndex("SymbolId");

                    b.HasIndex("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasIndex("InferenceId", "InferenceArgumentSerialNo")
                        .HasDatabaseName("IX_InferenceAssumptionDissolutableAssumptionFormulas_Inference~1");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentFromSerialNo")
                        .HasDatabaseName("IX_InferenceAssumptionDissolutableAssumptionFormulas_Inference~2");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasDatabaseName("IX_InferenceAssumptionDissolutableAssumptionFormulas_Inference~3");

                    b.ToTable("InferenceAssumptionDissolutableAssumptionFormulas");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionDissolutionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InferenceAssumptionDissolutionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "none"
                        },
                        new
                        {
                            Id = 2,
                            Name = "required"
                        },
                        new
                        {
                            Id = 3,
                            Name = "necessary"
                        });
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionFormula", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("InferenceAssumptionSerialNo")
                        .HasColumnType("int");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("BoundInferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<long?>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("InferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentFromSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentToSerialNo")
                        .HasColumnType("int");

                    b.Property<long?>("SymbolId")
                        .HasColumnType("bigint");

                    b.HasKey("InferenceId", "InferenceAssumptionSerialNo", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasIndex("InferenceId", "InferenceArgumentSerialNo");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentFromSerialNo");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasDatabaseName("IX_InferenceAssumptionFormulas_InferenceId_SubstitutionInferen~1");

                    b.ToTable("InferenceAssumptionFormulas");
                });

            modelBuilder.Entity("MathApi.Models.InferenceConclusionFormula", b =>
                {
                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<int>("SerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("BoundInferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<long?>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<int?>("InferenceArgumentSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentFromSerialNo")
                        .HasColumnType("int");

                    b.Property<int?>("SubstitutionInferenceArgumentToSerialNo")
                        .HasColumnType("int");

                    b.Property<long?>("SymbolId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("InferenceId", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasIndex("InferenceId", "InferenceArgumentSerialNo");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentFromSerialNo");

                    b.HasIndex("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasDatabaseName("IX_InferenceConclusionFormulas_InferenceId_SubstitutionInferen~1");

                    b.ToTable("InferenceConclusionFormulas");
                });

            modelBuilder.Entity("MathApi.Models.Proof", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "SerialNo");

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("MathApi.Models.ProofAssumption", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProofSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("AddedProofInferenceSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long?>("DissolutedProofInferenceSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.Property<long>("LastUsedProofInferenceSerialNo")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "ProofSerialNo", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.HasIndex("TheoremId", "ProofSerialNo", "AddedProofInferenceSerialNo")
                        .IsUnique();

                    b.HasIndex("TheoremId", "ProofSerialNo", "DissolutedProofInferenceSerialNo")
                        .IsUnique();

                    b.HasIndex("TheoremId", "ProofSerialNo", "LastUsedProofInferenceSerialNo")
                        .IsUnique();

                    b.ToTable("ProofAssumptions");
                });

            modelBuilder.Entity("MathApi.Models.ProofInference", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProofSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("ConclusionFormulaId")
                        .HasColumnType("bigint");

                    b.Property<long>("InferenceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NextProofInferenceSerialNo")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "ProofSerialNo", "SerialNo");

                    b.HasIndex("ConclusionFormulaId");

                    b.HasIndex("InferenceId");

                    b.HasIndex("TheoremId", "ProofSerialNo", "NextProofInferenceSerialNo");

                    b.ToTable("ProofInferences");
                });

            modelBuilder.Entity("MathApi.Models.ProofInferenceArgument", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProofSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("ProofInferenceSerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "ProofSerialNo", "ProofInferenceSerialNo", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.HasIndex("TheoremId", "SerialNo");

                    b.ToTable("ProofInferenceArguments");
                });

            modelBuilder.Entity("MathApi.Models.Symbol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int?>("Arity")
                        .HasColumnType("int");

                    b.Property<long?>("ArityFormulaTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Meaning")
                        .HasColumnType("longtext");

                    b.Property<long>("SymbolTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArityFormulaTypeId");

                    b.HasIndex("SymbolTypeId");

                    b.HasIndex("Character", "SymbolTypeId")
                        .IsUnique();

                    b.ToTable("Symbols");
                });

            modelBuilder.Entity("MathApi.Models.SymbolType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormulaTypeId");

                    b.ToTable("SymbolTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FormulaTypeId = 1L,
                            Name = "free variable"
                        },
                        new
                        {
                            Id = 2L,
                            FormulaTypeId = 1L,
                            Name = "bound variable"
                        },
                        new
                        {
                            Id = 3L,
                            FormulaTypeId = 2L,
                            Name = "proposition variable"
                        },
                        new
                        {
                            Id = 4L,
                            FormulaTypeId = 1L,
                            Name = "constant"
                        },
                        new
                        {
                            Id = 5L,
                            FormulaTypeId = 1L,
                            Name = "function"
                        },
                        new
                        {
                            Id = 6L,
                            FormulaTypeId = 2L,
                            Name = "predicate"
                        },
                        new
                        {
                            Id = 7L,
                            FormulaTypeId = 2L,
                            Name = "logic"
                        },
                        new
                        {
                            Id = 8L,
                            FormulaTypeId = 1L,
                            Name = "term quantifier"
                        },
                        new
                        {
                            Id = 9L,
                            FormulaTypeId = 2L,
                            Name = "proposition quantifier"
                        });
                });

            modelBuilder.Entity("MathApi.Models.Theorem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("IsProved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Theorems");
                });

            modelBuilder.Entity("MathApi.Models.TheoremAssumption", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.ToTable("TheoremAssumptions");
                });

            modelBuilder.Entity("MathApi.Models.TheoremConclusion", b =>
                {
                    b.Property<long>("TheoremId")
                        .HasColumnType("bigint");

                    b.Property<long>("SerialNo")
                        .HasColumnType("bigint");

                    b.Property<long>("FormulaId")
                        .HasColumnType("bigint");

                    b.HasKey("TheoremId", "SerialNo");

                    b.HasIndex("FormulaId");

                    b.ToTable("TheoremConclusions");
                });

            modelBuilder.Entity("MathApi.Models.AxiomProposition", b =>
                {
                    b.HasOne("MathApi.Models.Axiom", "Axiom")
                        .WithMany("AxiomPropositions")
                        .HasForeignKey("AxiomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("AxiomPropositions")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Axiom");

                    b.Navigation("Formula");
                });

            modelBuilder.Entity("MathApi.Models.FormulaChain", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("FormulaChains")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.FormulaString", "FromFormulaString")
                        .WithOne("FormulaChainAtFrom")
                        .HasForeignKey("MathApi.Models.FormulaChain", "FormulaId", "FromFormulaStringSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.FormulaString", "ToFormulaString")
                        .WithOne("FormulaChainAtTo")
                        .HasForeignKey("MathApi.Models.FormulaChain", "FormulaId", "ToFormulaStringSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("FromFormulaString");

                    b.Navigation("ToFormulaString");
                });

            modelBuilder.Entity("MathApi.Models.FormulaString", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("FormulaStrings")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Symbol", "Symbol")
                        .WithMany("FormulaStrings")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MathApi.Models.Inference", b =>
                {
                    b.HasOne("MathApi.Models.Theorem", "Theorem")
                        .WithOne("Inference")
                        .HasForeignKey("MathApi.Models.Inference", "TheoremId");

                    b.Navigation("Theorem");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgument", b =>
                {
                    b.HasOne("MathApi.Models.InferenceArgumentType", "InferenceArgumentType")
                        .WithMany("InferenceArguments")
                        .HasForeignKey("InferenceArgumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Inference", "Inference")
                        .WithMany("InferenceArguments")
                        .HasForeignKey("InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Symbol", "VariableSymbol")
                        .WithMany("InferenceArguments")
                        .HasForeignKey("VariableSymbolId");

                    b.Navigation("Inference");

                    b.Navigation("InferenceArgumentType");

                    b.Navigation("VariableSymbol");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgumentConstraint", b =>
                {
                    b.HasOne("MathApi.Models.InferenceArgument", "ConstraintDestinationInferenceArgument")
                        .WithMany("InferenceArgumentConstraintDistinations")
                        .HasForeignKey("InferenceId", "ConstraintDestinationInferenceArgumentSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.InferenceArgument", "InferenceArgument")
                        .WithMany("InferenceArgumentConstraints")
                        .HasForeignKey("InferenceId", "InferenceArgumentSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InferenceArgumentConstraints_InferenceArguments_InferenceId~1");

                    b.Navigation("ConstraintDestinationInferenceArgument");

                    b.Navigation("InferenceArgument");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumption", b =>
                {
                    b.HasOne("MathApi.Models.InferenceAssumptionDissolutionType", "InferenceAssumptionDissolutionType")
                        .WithMany("InferenceAssumptions")
                        .HasForeignKey("InferenceAssumptionDissolutionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Inference", "Inference")
                        .WithMany("InferenceAssumptions")
                        .HasForeignKey("InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inference");

                    b.Navigation("InferenceAssumptionDissolutionType");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionDissolutableAssumptionFormula", b =>
                {
                    b.HasOne("MathApi.Models.Symbol", "Symbol")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulas")
                        .HasForeignKey("SymbolId");

                    b.HasOne("MathApi.Models.InferenceArgument", "BoundInferenceArgument")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulasToBound")
                        .HasForeignKey("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "InferenceArgument")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulas")
                        .HasForeignKey("InferenceId", "InferenceArgumentSerialNo")
                        .HasConstraintName("FK_InferenceAssumptionDissolutableAssumptionFormulas_Inference~1");

                    b.HasOne("MathApi.Models.InferenceAssumption", "InferenceAssumption")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulas")
                        .HasForeignKey("InferenceId", "InferenceAssumptionSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InferenceAssumptionDissolutableAssumptionFormulas_Inference~2");

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentFrom")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulasToSubstitutionInferenceArgumentFrom")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentFromSerialNo")
                        .HasConstraintName("FK_InferenceAssumptionDissolutableAssumptionFormulas_Inference~3");

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentTo")
                        .WithMany("InferenceAssumptionDissolutableAssumptionFormulasToSubstitutionInferenceArgumentTo")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasConstraintName("FK_InferenceAssumptionDissolutableAssumptionFormulas_Inference~4");

                    b.Navigation("BoundInferenceArgument");

                    b.Navigation("InferenceArgument");

                    b.Navigation("InferenceAssumption");

                    b.Navigation("SubstitutionInferenceArgumentFrom");

                    b.Navigation("SubstitutionInferenceArgumentTo");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionFormula", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("InferenceAssumptionFormulas")
                        .HasForeignKey("FormulaId");

                    b.HasOne("MathApi.Models.Symbol", "Symbol")
                        .WithMany("InferenceAssumptionFormulas")
                        .HasForeignKey("SymbolId");

                    b.HasOne("MathApi.Models.InferenceArgument", "BoundInferenceArgument")
                        .WithMany("InferenceAssumptionFormulasToBound")
                        .HasForeignKey("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "InferenceArgument")
                        .WithMany("InferenceAssumptionFormulas")
                        .HasForeignKey("InferenceId", "InferenceArgumentSerialNo");

                    b.HasOne("MathApi.Models.InferenceAssumption", "InferenceAssumption")
                        .WithMany("InferenceAssumptionFormulas")
                        .HasForeignKey("InferenceId", "InferenceAssumptionSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentFrom")
                        .WithMany("InferenceAssumptionFormulasToSubstitutionInferenceArgumentFrom")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentFromSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentTo")
                        .WithMany("InferenceAssumptionFormulasToSubstitutionInferenceArgumentTo")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasConstraintName("FK_InferenceAssumptionFormulas_InferenceArguments_InferenceId_~1");

                    b.Navigation("BoundInferenceArgument");

                    b.Navigation("Formula");

                    b.Navigation("InferenceArgument");

                    b.Navigation("InferenceAssumption");

                    b.Navigation("SubstitutionInferenceArgumentFrom");

                    b.Navigation("SubstitutionInferenceArgumentTo");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MathApi.Models.InferenceConclusionFormula", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("InferenceConclusionFormulas")
                        .HasForeignKey("FormulaId");

                    b.HasOne("MathApi.Models.Inference", "Inference")
                        .WithMany("InferenceConclusionFormulas")
                        .HasForeignKey("InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Symbol", "Symbol")
                        .WithMany("InferenceConclusionFormulas")
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.InferenceArgument", "BoundInferenceArgument")
                        .WithMany("InferenceConclusionFormulasToBound")
                        .HasForeignKey("InferenceId", "BoundInferenceArgumentSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "InferenceArgument")
                        .WithMany("InferenceConclusionFormulas")
                        .HasForeignKey("InferenceId", "InferenceArgumentSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentFrom")
                        .WithMany("InferenceConclusionFormulasToSubstitutionInferenceArgumentFrom")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentFromSerialNo");

                    b.HasOne("MathApi.Models.InferenceArgument", "SubstitutionInferenceArgumentTo")
                        .WithMany("InferenceConclusionFormulasToSubstitutionInferenceArgumentTo")
                        .HasForeignKey("InferenceId", "SubstitutionInferenceArgumentToSerialNo")
                        .HasConstraintName("FK_InferenceConclusionFormulas_InferenceArguments_InferenceId_~1");

                    b.Navigation("BoundInferenceArgument");

                    b.Navigation("Formula");

                    b.Navigation("Inference");

                    b.Navigation("InferenceArgument");

                    b.Navigation("SubstitutionInferenceArgumentFrom");

                    b.Navigation("SubstitutionInferenceArgumentTo");

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("MathApi.Models.Proof", b =>
                {
                    b.HasOne("MathApi.Models.Theorem", "Theorem")
                        .WithMany("Proofs")
                        .HasForeignKey("TheoremId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theorem");
                });

            modelBuilder.Entity("MathApi.Models.ProofAssumption", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("ProofAssumptions")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Proof", "Proof")
                        .WithMany("ProofAssumptions")
                        .HasForeignKey("TheoremId", "ProofSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.ProofInference", "AddedProofInference")
                        .WithOne("AddingProofInference")
                        .HasForeignKey("MathApi.Models.ProofAssumption", "TheoremId", "ProofSerialNo", "AddedProofInferenceSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.ProofInference", "DissolutedProofInference")
                        .WithOne("DissolutingAssumption")
                        .HasForeignKey("MathApi.Models.ProofAssumption", "TheoremId", "ProofSerialNo", "DissolutedProofInferenceSerialNo");

                    b.HasOne("MathApi.Models.ProofInference", "LastUsedProofInference")
                        .WithOne("LastUsingProofInference")
                        .HasForeignKey("MathApi.Models.ProofAssumption", "TheoremId", "ProofSerialNo", "LastUsedProofInferenceSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedProofInference");

                    b.Navigation("DissolutedProofInference");

                    b.Navigation("Formula");

                    b.Navigation("LastUsedProofInference");

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("MathApi.Models.ProofInference", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "ConclusionFormula")
                        .WithMany("ProofInferences")
                        .HasForeignKey("ConclusionFormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Inference", "Inference")
                        .WithMany("ProofInferences")
                        .HasForeignKey("InferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Proof", "Proof")
                        .WithMany("ProofInferences")
                        .HasForeignKey("TheoremId", "ProofSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.ProofInference", "NextProofInference")
                        .WithMany("PreviousProofInferences")
                        .HasForeignKey("TheoremId", "ProofSerialNo", "NextProofInferenceSerialNo");

                    b.Navigation("ConclusionFormula");

                    b.Navigation("Inference");

                    b.Navigation("NextProofInference");

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("MathApi.Models.ProofInferenceArgument", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("ProofInferenceArguments")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.TheoremAssumption", null)
                        .WithMany("ProofInferenceArguments")
                        .HasForeignKey("TheoremId", "SerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.ProofInference", "ProofInference")
                        .WithMany("ProofInferenceArguments")
                        .HasForeignKey("TheoremId", "ProofSerialNo", "ProofInferenceSerialNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("ProofInference");
                });

            modelBuilder.Entity("MathApi.Models.Symbol", b =>
                {
                    b.HasOne("MathApi.Models.FormulaType", "ArityFormulaType")
                        .WithMany("Symbols")
                        .HasForeignKey("ArityFormulaTypeId");

                    b.HasOne("MathApi.Models.SymbolType", "SymbolType")
                        .WithMany("Symbols")
                        .HasForeignKey("SymbolTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArityFormulaType");

                    b.Navigation("SymbolType");
                });

            modelBuilder.Entity("MathApi.Models.SymbolType", b =>
                {
                    b.HasOne("MathApi.Models.FormulaType", "FormulaType")
                        .WithMany("SymbolTypes")
                        .HasForeignKey("FormulaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormulaType");
                });

            modelBuilder.Entity("MathApi.Models.TheoremAssumption", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("TheoremAssumptions")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Theorem", "Theorem")
                        .WithMany("TheoremAssumptions")
                        .HasForeignKey("TheoremId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("Theorem");
                });

            modelBuilder.Entity("MathApi.Models.TheoremConclusion", b =>
                {
                    b.HasOne("MathApi.Models.Formula", "Formula")
                        .WithMany("TheoremConclusions")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathApi.Models.Theorem", "Theorem")
                        .WithMany("TheoremConclusions")
                        .HasForeignKey("TheoremId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formula");

                    b.Navigation("Theorem");
                });

            modelBuilder.Entity("MathApi.Models.Axiom", b =>
                {
                    b.Navigation("AxiomPropositions");
                });

            modelBuilder.Entity("MathApi.Models.Formula", b =>
                {
                    b.Navigation("AxiomPropositions");

                    b.Navigation("FormulaChains");

                    b.Navigation("FormulaStrings");

                    b.Navigation("InferenceAssumptionFormulas");

                    b.Navigation("InferenceConclusionFormulas");

                    b.Navigation("ProofAssumptions");

                    b.Navigation("ProofInferenceArguments");

                    b.Navigation("ProofInferences");

                    b.Navigation("TheoremAssumptions");

                    b.Navigation("TheoremConclusions");
                });

            modelBuilder.Entity("MathApi.Models.FormulaString", b =>
                {
                    b.Navigation("FormulaChainAtFrom");

                    b.Navigation("FormulaChainAtTo");
                });

            modelBuilder.Entity("MathApi.Models.FormulaType", b =>
                {
                    b.Navigation("SymbolTypes");

                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("MathApi.Models.Inference", b =>
                {
                    b.Navigation("InferenceArguments");

                    b.Navigation("InferenceAssumptions");

                    b.Navigation("InferenceConclusionFormulas");

                    b.Navigation("ProofInferences");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgument", b =>
                {
                    b.Navigation("InferenceArgumentConstraintDistinations");

                    b.Navigation("InferenceArgumentConstraints");

                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulas");

                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulasToBound");

                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulasToSubstitutionInferenceArgumentFrom");

                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulasToSubstitutionInferenceArgumentTo");

                    b.Navigation("InferenceAssumptionFormulas");

                    b.Navigation("InferenceAssumptionFormulasToBound");

                    b.Navigation("InferenceAssumptionFormulasToSubstitutionInferenceArgumentFrom");

                    b.Navigation("InferenceAssumptionFormulasToSubstitutionInferenceArgumentTo");

                    b.Navigation("InferenceConclusionFormulas");

                    b.Navigation("InferenceConclusionFormulasToBound");

                    b.Navigation("InferenceConclusionFormulasToSubstitutionInferenceArgumentFrom");

                    b.Navigation("InferenceConclusionFormulasToSubstitutionInferenceArgumentTo");
                });

            modelBuilder.Entity("MathApi.Models.InferenceArgumentType", b =>
                {
                    b.Navigation("InferenceArguments");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumption", b =>
                {
                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulas");

                    b.Navigation("InferenceAssumptionFormulas");
                });

            modelBuilder.Entity("MathApi.Models.InferenceAssumptionDissolutionType", b =>
                {
                    b.Navigation("InferenceAssumptions");
                });

            modelBuilder.Entity("MathApi.Models.Proof", b =>
                {
                    b.Navigation("ProofAssumptions");

                    b.Navigation("ProofInferences");
                });

            modelBuilder.Entity("MathApi.Models.ProofInference", b =>
                {
                    b.Navigation("AddingProofInference");

                    b.Navigation("DissolutingAssumption");

                    b.Navigation("LastUsingProofInference");

                    b.Navigation("PreviousProofInferences");

                    b.Navigation("ProofInferenceArguments");
                });

            modelBuilder.Entity("MathApi.Models.Symbol", b =>
                {
                    b.Navigation("FormulaStrings");

                    b.Navigation("InferenceArguments");

                    b.Navigation("InferenceAssumptionDissolutableAssumptionFormulas");

                    b.Navigation("InferenceAssumptionFormulas");

                    b.Navigation("InferenceConclusionFormulas");
                });

            modelBuilder.Entity("MathApi.Models.SymbolType", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("MathApi.Models.Theorem", b =>
                {
                    b.Navigation("Inference");

                    b.Navigation("Proofs");

                    b.Navigation("TheoremAssumptions");

                    b.Navigation("TheoremConclusions");
                });

            modelBuilder.Entity("MathApi.Models.TheoremAssumption", b =>
                {
                    b.Navigation("ProofInferenceArguments");
                });
#pragma warning restore 612, 618
        }
    }
}
